#!/bin/bash

NAME=APP_NAME
DIR=PROJECT_DIR
APP_DIR=$DIR/PROJECT_SUBDIR/app
USER=ubuntu
GROUP=ubuntu
WORKERS=1
VENV=$DIR/.venv/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
WORKER_CLASS=uvicorn.workers.UvicornWorker
LOG_LEVEL=warning
MAX_REQUESTS=20
MAX_REQUESTS_JITTER=5

cd $APP_DIR
source $VENV

exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=- \
  --max-requests $MAX_REQUESTS \
  --max-requests-jitter $MAX_REQUESTS_JITTER \
